# Generated by Django 6.1.1 on 2026-09-26 13:56

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_actors_alter_movie_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=cinema.models.image_custom_path
            ),
        ),
    ]
